### ISSUE TITLE
小米mix2s手机安装后无法打开 闪退

### ISSUE THREAD

**Issue by zhang00829** [Sky24n/GreenTravel#1]
rt

**Comment by Sky24n** [comment]
你看下我的玩安卓app能不能运行，[flutter_wanandroid](https://raw.githubusercontent.com/Sky24n/LDocuments/master/AppStore/flutter_wanandroid.apk)

**Comment by Sky24n** [comment]
@zhanglei829 问题已修复，请重新下载安装～
