### ISSUE TITLE
地图插件 是用AndroidVIew，AndroidView在小米手机上会顶部留空白的

### ISSUE THREAD

**Issue by jicg** [Sky24n/GreenTravel#14]
如果地图插件 是用AndroidVIew 地图插件是如何处理AndroidView的小米手机偏移问题的啊？
如果不是使用的AndroidVIew，楼主是如何让原生的页面和 flutter页面混合到一起的啊？

**Comment by jicg** [comment]
@Sky24n 简单说下地图插件实现的想法呗！原生页面是如何和flutter页面混合到一起的啊？是否使用的AndroidView，如果使用AndroidView 如何处理[偏移问题](https://github.com/flutter/flutter/issues/24657)？

**Comment by Sky24n** [comment]
那个问题估计只有等官方修复!
地图插件直接参照Google地图。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
