### ISSUE TITLE
ERROR: Manifest merger failed 

### ISSUE THREAD

**Issue by zinwalin** [Sky24n/GreenTravel#19]
`ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at manifestMerger6286653408933565996.xml:7:5-9:19 to override.
`

**Comment by Sky24n** [comment]
pull最新代码
