### ISSUE TITLE
GreenTravelA 0.0.1版本bug&反馈

### ISSUE THREAD

**Issue by Sky24n** [Sky24n/GreenTravel#3]

**Comment by zhang00829** [comment]
![image](https://user-images.githubusercontent.com/40270286/53139233-fb265900-35c3-11e9-9d4a-e907bc32182e.png)
真机和模拟器运行 都不显示地图，是我哪里没配置好吗？

**Comment by Sky24n** [comment]
地图相关还没有开源呢

**Comment by zhang00829** [comment]
![image](https://user-images.githubusercontent.com/40270286/53294815-47260780-3829-11e9-9dbc-9236db1cb493.png)
![image](https://user-images.githubusercontent.com/40270286/53294816-5442f680-3829-11e9-9dbe-187e2b901e76.png)
<h3>webview 在ios上打不开</h3><br/>
貌似是flutter_webview 插件有问题 或者没有用好

**Comment by Sky24n** [comment]
@zhanglei829  需要打开UiKitView支持，pull 下代码。

**Comment by logney** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。没地图

**Comment by 54huige** [comment]
大佬 为什么不在项目下发起众筹 然后再开源不是更好吗

**Comment by Sky24n** [comment]
@54huige 很多人fork都不带star的，你觉得他们会给你众筹，想太多了吧

**Comment by 54huige** [comment]
> @54huige 很多人fork都不带star的，你觉得他们会给你众筹，想太多了吧
有点变态 力量不喜欢往一处使

**Comment by Sky24n** [comment]
@54huige 这个项目fork里面有超过一半的人，flutter_wanandroid项目fork里面有一百多人。瞬间就没有开源的心情了

**Comment by 54huige** [comment]
> @54huige 这个项目fork里面有超过一半的人，flutter_wanandroid项目fork里面有一百多人。瞬间就没有开源的心情了

作者开源项目本身就需要支持 很多能做下去的开源项目都是靠众筹 不然开源持续不下去 不懂这些人怎么想的

**Comment by fi-ecavc** [comment]
地图部分又开原计划吗？

**Comment by fi-ecavc** [comment]
地图部分有开源计划吗？有没有附近搜索功能？

**Comment by Sky24n** [comment]
> 地图部分有开源计划吗？有没有附近搜索功能？

不会开源了，就是因为太多人像你这样的，fork别人的代码，连个star都没有，fork过去后还自己给自己star！
![](https://user-images.githubusercontent.com/15412262/53647062-a2b42300-3c77-11e9-8904-da36c47e712b.jpeg)

**Comment by 54huige** [comment]
> 地图部分有开源计划吗？有没有附近搜索功能？

组队吧 没有支持 作者很难继续的 不说钱方面 至少精神方面要有支持 我蛮想众筹项目 支持作者开源

**Comment by fi-ecavc** [comment]
> > 地图部分有开源计划吗？有没有附近搜索功能？
> 
> 不会开源了，就是因为太多人像你这样的，fork别人的代码，连个star都没有，fork过去后还自己给自己star！
> ![](https://user-images.githubusercontent.com/15412262/53647062-a2b42300-3c77-11e9-8904-da36c47e712b.jpeg)

兄弟，你那么在乎star？fork的时候已经star了啊

**Comment by fi-ecavc** [comment]
> > 地图部分有开源计划吗？有没有附近搜索功能？
> 
> 不会开源了，就是因为太多人像你这样的，fork别人的代码，连个star都没有，fork过去后还自己给自己star！
> ![](https://user-images.githubusercontent.com/15412262/53647062-a2b42300-3c77-11e9-8904-da36c47e712b.jpeg)

现在就删除对你这个项目的fork，省的你不爽！

**Comment by Sky24n** [comment]
@54huige 你可以看哈楼上那位兄弟，fork代码连个star都没有，fork过来后自己给自己star，看到很多这种情况，心情就很复杂

**Comment by 54huige** [comment]
> @54huige 你可以看哈楼上那位兄弟，fork代码连个star都没有，fork过来后自己给自己star，看到很多这种情况，心情就很复杂

心疼作者 之前我也开源过东西 最后我把项目都删除了 确实没任何支持 一点开源动力都没了
