### ISSUE TITLE
GreenTravelA 0.0.2版本bug&反馈

### ISSUE THREAD

**Issue by iT-lijun** [Sky24n/GreenTravel#6]
版本：GreenTravelA 0.0.2
机型：小米MIX3
问题：UI宽高没适配 底下面黑了一截 详见截图样例
样例：
![Screenshot_2019-03-13-12-47-27-347_com thl greent](https://user-images.githubusercontent.com/11952091/54254646-82496a00-458f-11e9-8e9e-fe534f517931.png)
![Screenshot_2019-03-13-12-51-09-420_com thl greent](https://user-images.githubusercontent.com/11952091/54254642-7e1d4c80-458f-11e9-818f-bbd40efdad8d.png)

**Comment by Sky24n** [comment]
这边为了免权限降低了sdk版本引起的，当然你的手机可以设置开启强制全面屏的。
