### ISSUE TITLE
最核心的地图插件什么时候开源

### ISSUE THREAD

**Issue by unreal0** [Sky24n/GreenTravel#9]
最核心的地图插件什么时候开源.

**Comment by CodeGather** [comment]
应该不会有这个计划吧。

**Comment by unreal0** [comment]
哪个动态icon标记怎么做的?

**Comment by Davisjy** [comment]
➕1，求

**Comment by Sky24n** [comment]
> 
> 
> 哪个动态icon标记怎么做的?

不清楚你指的是什么

**Comment by Sky24n** [comment]
> 
> 
> ➕1，求

确定my_first_flutter是你自己写的入门demo？！

**Comment by Davisjy** [comment]
@Sky24n 是啊，中间也对比其他很多开源项目，不过不清楚有什么问题

**Comment by unreal0** [comment]
那个固定的定位maker的Widget,共享下呗

**Comment by SuperIOSDeveloper** [comment]
地图插件 怎么弄

**Comment by jicg** [comment]
看了楼主的打包的apk有地图，想研究研究。原来 地图没开源。。。

**Comment by luddite1989** [comment]
暂未开放，敬请期待，是什么鬼？

**Comment by Sky24n** [comment]
> 暂未开放，敬请期待，是什么鬼？

已重新打包。
